export const LOGO = "./assets/images/logo.svg"
export const BACKGROUND = "./assets/images/background.jpg"
export const MUSHROOM = "./assets/images/mushroom.svg"
export const NOTFOUND = "./assets/images/404.svg"
export const CROSS = "./assets/images/cross.svg"
export const CHECK = "./assets/images/check.svg"